#!/bin/bash
cd /home/ec2-user/ruby-on-rails
mkdir -p log

source /etc/profile.d/rvm.sh
rvm list
rvm gemset list
gem list

db_name=$(aws ssm get-parameters --region us-west-2 --names mazhuga-db-name  --with-decryption --query Parameters[0].Value)
db_name=`echo $db_name | sed -e 's/^"//' -e 's/"$//'`

db_user=$(aws ssm get-parameters --region us-west-2 --names mazhuga-db-user  --with-decryption --query Parameters[0].Value)
db_user=`echo $db_user | sed -e 's/^"//' -e 's/"$//'`

db_password=$(aws ssm get-parameters --region us-west-2 --names mazhuga-db-password  --with-decryption --query Parameters[0].Value)
db_password=`echo $db_password | sed -e 's/^"//' -e 's/"$//'`

db_host=$(aws ssm get-parameters --region us-west-2 --names mazhuga-db-host  --with-decryption --query Parameters[0].Value)
db_host=`echo $db_host | sed -e 's/^"//' -e 's/"$//'`

carier_wave_s3_bucket=$(aws ssm get-parameters --region us-west-2 --names mazhuga-CarierWaveS3BucketNameSSM  --with-decryption --query Parameters[0].Value)
carier_wave_s3_bucket=`echo $carier_wave_s3_bucket | sed -e 's/^"//' -e 's/"$//'`

user_access_key=$(aws ssm get-parameters --region us-west-2 --names mazhuga-IAMStackUserAccessKeySSM  --with-decryption --query Parameters[0].Value)
user_access_key=`echo $user_access_key | sed -e 's/^"//' -e 's/"$//'`

user_secret_access_key=$(aws ssm get-parameters --region us-west-2 --names mazhuga-IAMStackUserSecretAccessKeySSM  --with-decryption --query Parameters[0].Value)
user_secret_access_key=`echo $user_secret_access_key | sed -e 's/^"//' -e 's/"$//'`

[ -f .env ] && rm .env || echo .env is not exists yet

echo DATABASE=$db_name >> .env
echo DATABASE_USERNAME=$db_user >> .env
echo DATABASE_PASSWORD=$db_password >> .env
echo DATABASE_HOST=$db_host >> .env
echo RAILS_ENV=production >> .env
echo RAKE_ENV=production >> .env
echo DEVISE_SECRET=8db1b8d5158b97eb7b54bf002765323c04a5c1be86d34b44548637f6e7a358e160a078390957e5481b069761e8b8c1dcd0489cb0fa2ab302071d878634878161 >> .env
echo DAEMONIZE_PUMA=true >> .env
echo PORT=80 >> .env

echo AWS_ACCESS_KEY_ID=$user_access_key >> .env
echo AWS_SECRET_ACCESS_KEY=$user_secret_access_key >> .env
echo AWS_DEFAULT_S3_BUCKET=$carier_wave_s3_bucket >> .env
echo AWS_S3_REGION=us-west-2 >> .env

echo Copy project specific variables to .env
cat .env.custom >> .env

#rvm requirements
#rvm install 2.3.3

#curl -sL https://rpm.nodesource.com/setup | bash -
#yum install -y nodejs

gem install bundler -v 1.17.0
bundle install --without development test

export SECRET_KEY_BASE="$(bundle exec rake secret)"
